authors:
  jonathanduncan:
    name: Jonathan Duncan
    description: Freelance Software & AI Engineer
    avatar: ../assets/linkedin_headshot_330.png
    url: https://www.linkedin.com/in/jonathanduncan/