authors:
  jonathanduncan:
    name: Jonathan Duncan
    description: Freelance Software & AI Engineer | Helping Businesses Automate Workflows with Custom-Built AI Enabled Solutions | $500K+ Earnings on Upwork | Top Rated Plus
    avatar: ../assets/linkedin_headshot_400.png
    url: https://www.linkedin.com/in/jonathanduncan/